import { mkdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import {
  createTask,
  createTeam,
  formatDisplayPath,
  getDefaultWorkspacePath,
  getTaskListIdForTeam,
  readTeamFile,
  resetTaskList,
  sanitizePathComponent,
  type TeamCoreOptions,
  type TeamRuntimeKind,
} from '../../team-core/index.js'
import {
  buildSoftwareFactoryAgentSpecs,
  REVIEWER_DEPENDENCY_ROLES,
  WORKSPACE_DIRECTORIES,
  type SoftwareFactoryAgentSpec,
} from '../presets/index.js'
import { launchBackgroundAgentTeamCommand } from '../../team-operator/background-process.js'
import { runSendCommand } from './send.js'
import type { CliCommandResult } from '../types.js'

export type RunPresetName = 'software-factory'

export type RunCommandInput = {
  goal: string
  workspace?: string
  teamName?: string
  preset?: RunPresetName
  runtimeKind?: TeamRuntimeKind
  model?: string
  maxIterations?: number
  pollIntervalMs?: number
  codexExecutablePath?: string
  upstreamExecutablePath?: string
  codexArgs?: string[]
  upstreamArgs?: string[]
}

export type RunCommandDependencies = {
  launchBackgroundAgentTeamCommand: typeof launchBackgroundAgentTeamCommand
  now: () => number
}

const defaultRunCommandDependencies: RunCommandDependencies = {
  launchBackgroundAgentTeamCommand,
  now: () => Date.now(),
}

function createDefaultTeamName(goal: string, now: number): string {
  const sanitized = sanitizePathComponent(goal)
    .toLowerCase()
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 24)

  const prefix = sanitized.length > 0 ? sanitized : 'run'
  return `${prefix}-${now.toString(36)}`
}

function resolveWorkspacePath(
  workspace: string | undefined,
  options: TeamCoreOptions,
  teamName: string,
): string {
  if (workspace) {
    return resolve(workspace)
  }
  return getDefaultWorkspacePath(teamName, options)
}

function buildDefaultCodexArgs(input: RunCommandInput): string[] {
  const defaults = ['--full-auto']
  return [...defaults, ...(input.codexArgs ?? [])]
}

async function createWorkspaceBootstrapFiles(
  goal: string,
  workspacePath: string,
  teamName: string,
  preset: RunPresetName,
  runtimeKind: TeamRuntimeKind,
): Promise<void> {
  const [docsDir, frontendDir, backendDir] = WORKSPACE_DIRECTORIES.map(dir =>
    join(workspacePath, dir),
  )
  const internalDir = join(workspacePath, '.agent-team')

  await Promise.all([
    mkdir(workspacePath, { recursive: true }),
    mkdir(docsDir, { recursive: true }),
    mkdir(frontendDir, { recursive: true }),
    mkdir(backendDir, { recursive: true }),
    mkdir(internalDir, { recursive: true }),
  ])

  await writeFile(
    join(docsDir, 'goal.md'),
    [
      '# Project Goal',
      '',
      `- Goal: ${goal}`,
      `- Team: ${teamName}`,
      `- Preset: ${preset}`,
      `- Runtime: ${runtimeKind}`,
      '',
      'This file was generated by `agent-team run`.',
    ].join('\n') + '\n',
    'utf8',
  )

  await writeFile(
    join(internalDir, 'run.json'),
    JSON.stringify(
      {
        goal,
        teamName,
        preset,
        runtimeKind,
        workspacePath,
        createdAt: new Date().toISOString(),
      },
      null,
      2,
    ) + '\n',
    'utf8',
  )
}

function buildBackgroundSpawnArgs(
  input: {
    teamName: string
    agentName: string
    prompt: string
    cwd: string
    runtimeKind: TeamRuntimeKind
    model?: string
    maxIterations: number
    pollIntervalMs?: number
    codexExecutablePath?: string
    upstreamExecutablePath?: string
    codexArgs?: string[]
    upstreamArgs?: string[]
  },
  options: TeamCoreOptions,
): string[] {
  const args: string[] = []

  if (options.rootDir) {
    args.push('--root-dir', options.rootDir)
  }

  args.push(
    'spawn',
    input.teamName,
    input.agentName,
    '--prompt',
    input.prompt,
    '--cwd',
    input.cwd,
    '--runtime',
    input.runtimeKind,
    '--max-iterations',
    String(input.maxIterations),
  )

  if (input.pollIntervalMs) {
    args.push('--poll-interval', String(input.pollIntervalMs))
  }
  if (input.model) {
    args.push('--model', input.model)
  }
  if (input.codexExecutablePath) {
    args.push('--codex-executable', input.codexExecutablePath)
  }
  if (input.upstreamExecutablePath) {
    args.push('--upstream-executable', input.upstreamExecutablePath)
  }
  for (const codexArg of input.codexArgs ?? []) {
    args.push('--codex-arg', codexArg)
  }
  for (const upstreamArg of input.upstreamArgs ?? []) {
    args.push('--upstream-arg', upstreamArg)
  }

  return args
}

function renderCliInvocation(
  args: string[],
  options: TeamCoreOptions,
): string {
  const segments = [
    'agent-team',
    ...(options.rootDir
      ? ['--root-dir', formatDisplayPath(options.rootDir) ?? options.rootDir]
      : []),
    ...args,
  ]

  return segments
    .map(segment =>
      /\s/.test(segment) ? JSON.stringify(segment) : segment,
    )
    .join(' ')
}

export async function runRunCommand(
  input: RunCommandInput,
  options: TeamCoreOptions = {},
  dependencies: Partial<RunCommandDependencies> = {},
): Promise<CliCommandResult> {
  const resolvedDependencies = {
    ...defaultRunCommandDependencies,
    ...dependencies,
  } satisfies RunCommandDependencies

  const goal = input.goal.trim()
  if (goal.length === 0) {
    return {
      success: false,
      message: 'Missing run goal',
    }
  }

  const preset = input.preset ?? 'software-factory'
  const runtimeKind = input.runtimeKind ?? 'codex-cli'
  const teamName =
    input.teamName ??
    createDefaultTeamName(goal, resolvedDependencies.now())
  const workspacePath = resolveWorkspacePath(input.workspace, options, teamName)

  if (await readTeamFile(teamName, options)) {
    return {
      success: false,
      message: `Team "${teamName}" already exists`,
    }
  }

  await createWorkspaceBootstrapFiles(
    goal,
    workspacePath,
    teamName,
    preset,
    runtimeKind,
  )

  await createTeam(
    {
      teamName,
      description: goal,
      leadAgentId: `team-lead@${teamName}`,
      leadMember: {
        name: 'team-lead',
        agentType: 'team-lead',
        cwd: workspacePath,
        subscriptions: [],
      },
    },
    options,
  )
  const taskListId = getTaskListIdForTeam(teamName)
  await resetTaskList(taskListId, options)

  const codexArgs =
    runtimeKind === 'codex-cli' ? buildDefaultCodexArgs(input) : input.codexArgs
  const agents = buildSoftwareFactoryAgentSpecs(
    goal,
    workspacePath,
    teamName,
    codexArgs ?? [],
  )
  const taskIdsByRole = new Map<SoftwareFactoryAgentSpec['role'], string>()

  for (const agent of agents) {
    const task = await createTask(
      taskListId,
      {
        ...agent.task,
        blockedBy:
          agent.role === 'reviewer'
            ? REVIEWER_DEPENDENCY_ROLES.map(role => taskIdsByRole.get(role)).filter(
                (taskId): taskId is string => taskId !== undefined,
              )
            : agent.task.blockedBy,
      },
      options,
    )
    taskIdsByRole.set(agent.role, task.id)
    await runSendCommand(teamName, agent.name, agent.leaderMessage, options)
  }

  const launchResults = []
  for (const agent of agents) {
    const launched = await resolvedDependencies.launchBackgroundAgentTeamCommand(
      buildBackgroundSpawnArgs(
        {
          teamName,
          agentName: agent.name,
          prompt: agent.prompt,
          cwd: workspacePath,
          runtimeKind,
          model: input.model,
          maxIterations: input.maxIterations ?? 8,
          pollIntervalMs: input.pollIntervalMs,
          codexExecutablePath: input.codexExecutablePath,
          upstreamExecutablePath: input.upstreamExecutablePath,
          codexArgs: agent.codexArgs,
          upstreamArgs: input.upstreamArgs,
        },
        options,
      ),
    )

    launchResults.push({
      agent: agent.name,
      ...launched,
    })

    if (!launched.success) {
      return {
        success: false,
        message:
          `Failed to launch ${agent.name} for team "${teamName}": ` +
          (launched.error ?? 'unknown error'),
      }
    }
  }

  const watchCommand = renderCliInvocation(['watch', teamName], options)
  const tuiCommand = renderCliInvocation(['tui', teamName], options)
  const statusCommand = renderCliInvocation(['status', teamName], options)
  const attachCommand = renderCliInvocation(['attach', teamName], options)

  return {
    success: true,
    message: [
      `Started ${preset} team "${teamName}" for goal: ${goal}`,
      `workspace=${formatDisplayPath(workspacePath) ?? workspacePath}`,
      `runtime=${runtimeKind}`,
      `launched=${launchResults.length}`,
      ...launchResults.map(
        launched =>
          `- ${launched.agent} pid=${launched.pid ?? 'n/a'} command=${launched.command}`,
      ),
      '',
      'Next steps:',
      `- Attach: ${attachCommand}`,
      `- Watch: ${watchCommand}`,
      `- TUI:   ${tuiCommand}`,
      `- Status: ${statusCommand}`,
    ].join('\n'),
  }
}
